run:
  tests: false

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  dupl:
    threshold: 100
  lll:
    line-length: 140

linters:
  enable:
    - bodyclose
    - dupl
    - goimports
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
