name: Commit

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run base workflow
        uses: ./.github/actions/base
        with:
          go-version: '1.23'
